### ISSUE TITLE
operator设置doris管理员AdminUser配置项不生效

### ISSUE THREAD

**Issue by anthony-yau** [apache/doris-operator#131]
版本：1.4.1（当前最新)

通过设置 [AdminUser](https://github.com/selectdb/doris-operator/blob/master/doc/api.md#doris.selectdb.com/v1.AdminUser) 后不能完成设置管理员密码的功能，是还没实现吗？

**Comment by intelligentfu** [comment]
已经实现，请贴一下现象，doriscluster的yaml以及环境。

**Comment by anthony-yau** [comment]
> 已经实现，请贴一下现象，doriscluster的yaml以及环境。

yaml文件：
```
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doris-testxx
    app.kubernetes.io/instance: doris-testxx
    app.kubernetes.io/part-of: doris-operator
  name: doris-testxx
  namespace: default
spec:
  adminUser:
    name: dsadmin
    password: DSf@x2412
  # FE配置
  feSpec:
    # 指定参与选举的数量，其他的为仲裁节点
    electionNumber: 3
    # 副本数, 1主2从
    replicas: 3
    image: xxx
    # 配置服务类型, 如果要在集群外访问，需要使用LoadBalancer等类型
    service:
      type: "ClusterIP"
    # 资源配置
    requests:
      cpu: 8
      memory: 16Gi
    limits:
      cpu: 16
      memory: 32Gi
    # 持久化配置
    persistentVolumes:
    - mountPath: /opt/apache-doris/fe/doris-meta
      name: femeta
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
    - mountPath: /opt/apache-doris/fe/log
      name: felog
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
    # 初始配置
    systemInitialization:
      command: [ "/sbin/sysctl", "-w", "vm.max_map_count=2000000" ]
  # BE配置
  beSpec:
    # 副本数
    replicas: 3
    image: xxx
    # 资源配置
    requests:
      cpu: 8
      memory: 16Gi
    limits:
      cpu: 16
      memory: 64Gi
    # 持久化配置
    persistentVolumes:
    - mountPath: /opt/apache-doris/be/storage
      name: bedata
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
    - mountPath: /opt/apache-doris/be/log
      name: belog
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
    # 初始配置
    systemInitialization:
      command: [ "/sbin/sysctl", "-w", "vm.max_map_count=2000000" ]
```

 # kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.5-tke.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.5-tke.15", Compiler:"gc", Platform:"linux/amd64"}

# doris operator
spec:
  containers:
  - args:
    - --leader-elect
    command:
    - /dorisoperator
    image: selectdb/doris.k8s-operator:latest
    imagePullPolicy: Always
