### ISSUE TITLE
DorisCluster create failed permission denied: unknown

### ISSUE THREAD

**Issue by lanss315425** [apache/doris-operator#183]
selectdb/doris.k8s-operator:1.6.0

```
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster-sample
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster-sample
spec:
  feSpec:
    configMapInfo:
      configMapName: doriscluster-sample-conf
      resolveKey: fe.conf
    securityContext: # 新增部分
      runAsUser: 0 # 允许容器以root用户运行
    replicas: 3
    service:
      type: NodePort
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
    image:  selectdb/doris.fe-ubuntu:2.0.11
    envVars:
      - name: TZ
        value: "Asia/Shanghai"
    persistentVolumes:
      - mountPath: /opt/apache-doris/fe/doris-meta
        name: fe-doris-meta
        persistentVolumeClaimSpec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - mountPath: /opt/apache-doris/fe/log
        name: fe-log
        persistentVolumeClaimSpec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  beSpec:
    configMapInfo:
      configMapName: doriscluster-sample-conf
      resolveKey: be.conf
    replicas: 3
    securityContext: # 新增部分
      runAsUser: 0 # 允许容器以root用户运行
    service:
      type: NodePort
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
    image: selectdb/doris.be-ubuntu:2.0.11
    envVars:
      - name: TZ
        value: "Asia/Shanghai"
    persistentVolumes:
      - mountPath: /opt/apache-doris/be/storage
        name: be-storage
        persistentVolumeClaimSpec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - mountPath: /opt/apache-doris/be/log
        name: be-log
        persistentVolumeClaimSpec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

errlog：
```
  Normal   Created    7m16s (x4 over 8m8s)  kubelet            Created container fe
  Warning  Failed     7m16s (x4 over 8m8s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/apache-doris/fe_entrypoint.sh": permission denied: unknown
  Warning  BackOff    3m (x34 over 8m7s)    kubelet            Back-off restarting failed container fe in pod doriscluster-sample-fe-0_doris(15869920-5ff4-4bf4-9da9-3502a47a4cf4)
```
